# Generated by Django 5.0.1 on 2025-12-14 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owner_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], max_length=20)),
                ('engine_number', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100)),
                ('insurance_expiry', models.DateField()),
                ('pollution_certificate_expiry', models.DateField()),
                ('registration_date', models.DateField()),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('logo', models.ImageField(blank=True, upload_to='vehicle_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
