# Generated by Django 5.0.1 on 2025-12-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/pollution/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
