# Generated by Django 5.0.1 on 2025-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_insurance_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/rc/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
