# Generated by Django 5.0.1 on 2025-12-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_rc_certificate_vehicle_rc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pollution_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pollution_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rc_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rc_number',
        ),
    ]
